create table question (
  id bigint generated by default as identity not null primary key,
  question varchar(255) not null,
  answer varchar(255) not null
);

create table answer (
  id bigint generated by default as identity not null primary key,
  correct boolean not null,
  answer_date timestamp default now,
  question_id bigint not null,
  constraint answer_question_id foreign key (question_id) references question (id)
);

